version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  web:
    build: .
    container_name: webworker
    volumes:
      - imgdata:/code/static/storage
    ports:
      - '8080:8080'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2


volumes:
  esdata1:
    driver: local
  imgdata:
    driver: local

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1